// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_AboutImage2Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_AboutImage2Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202107071047317_mig_AboutImage2Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
